# 넘파이 Numpy

In [4]:
import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]


In [4]:
arr1 = np.array(data1)
arr2 = np.array(data2)

arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [ ]:
arr1. shape , arr1.dtype # 모양, 타입 뽑아냄

((5,), dtype('int64'))

In [7]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3 

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3.shape , arr3.dtype

((2, 3), dtype('int64'))

In [11]:
zz = np.zeros(10)
zz, zz.shape , zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [13]:
zzz = np.zeros((3,5))
zzz, zzz.shape , zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [14]:
oo = np.ones(7)
oo, oo.shape , oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [15]:
ooo = np.ones((2,10))
ooo, ooo.shape , ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [19]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [21]:
print(arr1.shape, arr1.dtype)
print(arr2.shape, arr2.dtype)

(2, 3) int64
(2, 3) int64


In [29]:

result0 = arr1*3
result1 = arr1 +arr2
result2 = arr1 -arr2
result3 = arr1*2 -arr2/10
result4 = arr1*arr2
result5 = arr1/arr2
# 브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])

print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(arr1+arr3)
print(arr1*arr3)

[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[23 35 47]
 [26 38 50]]
[[ 22  66 132]
 [ 88 165 264]]


# 1차원

In [3]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의개수
arr = np.arange(5)
arr, arr.shape, arr.dtype , arr.size , arr.ndim


NameError: name 'np' is not defined

In [32]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype = 'str')

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [42]:
arr4 = np.full((4,3),"nope")
arr4
arr5 = np.eye(3)
arr5
arr6 = np.linspace(0,300,15 , endpoint = False, dtype="int64")
print(arr6)
arr7 = np.arange(0,100,20)
print(arr7)

[  0  20  40  60  80 100 120 140 160 180 200 220 240 260 280]
[ 0 20 40 60 80]


# 2차원

In [6]:
arr20 = np.array([[1,2],[3,4]])
arr20 , arr20.shape , arr20.size, arr20.dtype, arr20.ndim , type(arr20)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [8]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21 , arr21.shape , arr21.size, arr21.dtype, arr21.ndim , type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22 , arr22.shape , arr22.size, arr22.dtype, arr22.ndim , type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23 , arr23.shape , arr23.size, arr23.dtype, arr23.ndim , type(arr23))
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요:",e)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>


## 인덱싱(마스크)

In [7]:
# 난수 발생
import  numpy as np
ran_data = np.random.randn(8,4)
ran_data

array([[ 1.02979369,  0.22422559,  0.56012114,  0.82790594],
       [ 0.03925628, -0.43197187, -1.30997476,  1.61871523],
       [-0.4851426 , -0.33582042,  0.93261283,  1.4408495 ],
       [-1.4249151 ,  0.44374138,  0.96073953, -1.30064258],
       [ 0.82013684,  0.03972012,  1.24123769, -1.1442716 ],
       [-0.6135811 ,  1.03831581,  0.28167551,  0.03187085],
       [ 0.65082322,  0.09326696,  0.15598218, -0.17528246],
       [-0.03548153,  1.95501189,  0.03101583, -0.96902681]])

In [5]:
mask = np.array([True,False,True,False,False,True,True,False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [8]:
ran_data[mask]

array([[ 1.02979369,  0.22422559,  0.56012114,  0.82790594],
       [-0.4851426 , -0.33582042,  0.93261283,  1.4408495 ],
       [-0.6135811 ,  1.03831581,  0.28167551,  0.03187085],
       [ 0.65082322,  0.09326696,  0.15598218, -0.17528246]])

In [9]:
fruit = np.array(['apple','banana','apple','kiwi','orange','apple','apple','melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [ ]:
fruit_mask = (fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [11]:
ran_data[fruit_mask]

array([[ 1.02979369,  0.22422559,  0.56012114,  0.82790594],
       [-0.4851426 , -0.33582042,  0.93261283,  1.4408495 ],
       [-0.6135811 ,  1.03831581,  0.28167551,  0.03187085],
       [ 0.65082322,  0.09326696,  0.15598218, -0.17528246]])

In [20]:
ran_data[ (fruit == 'apple') | (fruit == 'orange') ,1:3] #ran_data[행,열]

array([[ 0.22422559,  0.56012114],
       [-0.33582042,  0.93261283],
       [ 0.03972012,  1.24123769],
       [ 1.03831581,  0.28167551],
       [ 0.09326696,  0.15598218]])

## 인덱스와 마스크의 응용

In [23]:
ran_data[:,0] >0

array([ True,  True, False, False,  True, False,  True, False])

In [ ]:
ran_data[ran_data[:,:] >0]

array([1.02979369, 0.22422559, 0.56012114, 0.82790594, 0.03925628,
       1.61871523, 0.93261283, 1.4408495 , 0.44374138, 0.96073953,
       0.82013684, 0.03972012, 1.24123769, 1.03831581, 0.28167551,
       0.03187085, 0.65082322, 0.09326696, 0.15598218, 1.95501189,
       0.03101583])

In [64]:
fl = ran_data[ran_data[:,0] <0 ,1:3]
fl

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
fl = ran_data[ran_data[:,0] <0 ,1:3]
fl_zeros = np.zeros_like(fl)
ran_data[ran_data[:,0] <0 ,1:3] = np.nan #np.nan
ran_data

array([[ 1.02979369,  0.22422559,  0.56012114,  0.82790594],
       [ 0.03925628, -0.43197187, -1.30997476,  1.61871523],
       [-0.4851426 ,         nan,         nan,  1.4408495 ],
       [-1.4249151 ,         nan,         nan, -1.30064258],
       [ 0.82013684,  0.03972012,  1.24123769, -1.1442716 ],
       [-0.6135811 ,         nan,         nan,  0.03187085],
       [ 0.65082322,  0.09326696,  0.15598218, -0.17528246],
       [-0.03548153,         nan,         nan, -0.96902681]])

In [69]:
np.isnan(ran_data)
#ran_data == 'nan'

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True, False]])

In [81]:
f2 = ran_data[np.isnan(ran_data).any(axis=1)]
f2

array([[-0.4851426 ,         nan,         nan,  1.4408495 ],
       [-1.4249151 ,         nan,         nan, -1.30064258],
       [-0.6135811 ,         nan,         nan,  0.03187085],
       [-0.03548153,         nan,         nan, -0.96902681]])

In [82]:
f3 = ran_data[~np.isnan(ran_data).any(axis=1)]
f3

array([[ 1.02979369,  0.22422559,  0.56012114,  0.82790594],
       [ 0.03925628, -0.43197187, -1.30997476,  1.61871523],
       [ 0.82013684,  0.03972012,  1.24123769, -1.1442716 ],
       [ 0.65082322,  0.09326696,  0.15598218, -0.17528246]])

In [85]:
f4 = np.abs(f3)
f4

array([[1.02979369, 0.22422559, 0.56012114, 0.82790594],
       [0.03925628, 0.43197187, 1.30997476, 1.61871523],
       [0.82013684, 0.03972012, 1.24123769, 1.1442716 ],
       [0.65082322, 0.09326696, 0.15598218, 0.17528246]])

In [87]:
f5 = np.sqrt(f4)
f5

array([[1.01478751, 0.47352465, 0.74841241, 0.90989337],
       [0.19813197, 0.65724567, 1.14454129, 1.2722874 ],
       [0.90561407, 0.19929907, 1.11410847, 1.06970631],
       [0.80673615, 0.3053964 , 0.3949458 , 0.41866748]])

In [88]:
f6 = np.log(f5)
f6

array([[ 0.01467924, -0.74755132, -0.2898011 , -0.09442786],
       [-1.61882195, -0.41969741,  0.13500393,  0.24081638],
       [-0.09914204, -1.61294871,  0.10805451,  0.06738414],
       [-0.21475861, -1.18614469, -0.92900675, -0.87067827]])

In [89]:
np.sign(f6)

array([[ 1., -1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [-1., -1.,  1.,  1.],
       [-1., -1., -1., -1.]])

In [ ]:
# 삼각함수 값을 계산하기 (cos, sin, tan, cosh, sinh, tanh)
np.cos(f6)

array([[ 0.99989226,  0.73335579,  0.95830073,  0.995545  ],
       [-0.04800716,  0.91321228,  0.9909008 ,  0.9711436 ],
       [ 0.99508945, -0.0421399 ,  0.99416779,  0.99773055],
       [ 0.97702787,  0.37523625,  0.5986299 ,  0.64430798]])

In [92]:
# 두개의 array에 동일한 위치의 요소끼리 비교하기
data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1 , data2

(array([[ 0.09756623,  0.41185135,  0.20400507, -0.40682418],
        [-1.73320186,  2.09148508,  0.08027668, -2.13705088],
        [-2.07689664, -0.19994921, -0.87751396,  1.45547023],
        [-0.69701199, -0.48802097,  0.34784603,  2.25999064],
        [-1.58143786, -0.2089396 , -1.58411949, -2.01432136],
        [-0.3867379 , -2.55075204,  0.22861051,  2.42387537],
        [ 1.18318037,  2.12838333, -0.55009327,  1.22480156],
        [-0.69429782, -0.6786423 , -0.57747722,  0.12765587]]),
 array([[-0.39499618,  1.10906275, -0.99946391, -0.59338354],
        [ 1.24530068, -0.69101064, -0.70592977, -0.36693614],
        [ 0.58688908, -0.38738741, -2.03110672, -1.67680227],
        [-0.17902458,  0.9054133 , -1.13754129,  0.75662961],
        [ 0.24671768,  1.82459105, -0.32153104, -0.49151209],
        [-0.1350098 ,  0.57687075,  1.16121662, -1.59903388],
        [ 0.92067278, -0.41547924, -0.01061678, -0.69618081],
        [ 0.67646913, -0.57755336, -0.35218281,  1.43879676]]))

In [93]:
np.maximum(data1, data2)

array([[ 0.09756623,  1.10906275,  0.20400507, -0.40682418],
       [ 1.24530068,  2.09148508,  0.08027668, -0.36693614],
       [ 0.58688908, -0.19994921, -0.87751396,  1.45547023],
       [-0.17902458,  0.9054133 ,  0.34784603,  2.25999064],
       [ 0.24671768,  1.82459105, -0.32153104, -0.49151209],
       [-0.1350098 ,  0.57687075,  1.16121662,  2.42387537],
       [ 1.18318037,  2.12838333, -0.01061678,  1.22480156],
       [ 0.67646913, -0.57755336, -0.35218281,  1.43879676]])

In [94]:
np.minimum(data1, data2)

array([[-0.39499618,  0.41185135, -0.99946391, -0.59338354],
       [-1.73320186, -0.69101064, -0.70592977, -2.13705088],
       [-2.07689664, -0.38738741, -2.03110672, -1.67680227],
       [-0.69701199, -0.48802097, -1.13754129,  0.75662961],
       [-1.58143786, -0.2089396 , -1.58411949, -2.01432136],
       [-0.3867379 , -2.55075204,  0.22861051, -1.59903388],
       [ 0.92067278, -0.41547924, -0.55009327, -0.69618081],
       [-0.69429782, -0.6786423 , -0.57747722,  0.12765587]])

In [ ]:
np.maximum(data1 ,0) #Relu(x) 와 같다

array([[0.09756623, 0.41185135, 0.20400507, 0.        ],
       [0.        , 2.09148508, 0.08027668, 0.        ],
       [0.        , 0.        , 0.        , 1.45547023],
       [0.        , 0.        , 0.34784603, 2.25999064],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.22861051, 2.42387537],
       [1.18318037, 2.12838333, 0.        , 1.22480156],
       [0.        , 0.        , 0.        , 0.12765587]])

In [97]:
np.minimum(np.maximum(data2,0.5),1.7)

array([[0.5       , 1.10906275, 0.5       , 0.5       ],
       [1.24530068, 0.5       , 0.5       , 0.5       ],
       [0.58688908, 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.9054133 , 0.5       , 0.75662961],
       [0.5       , 1.7       , 0.5       , 0.5       ],
       [0.5       , 0.57687075, 1.16121662, 0.5       ],
       [0.92067278, 0.5       , 0.5       , 0.5       ],
       [0.67646913, 0.5       , 0.5       , 1.43879676]])

## 통계함수

In [104]:
data = np.random.randn(4,4)
data

array([[ 0.19827304, -1.09506825,  0.95735387, -1.06763686],
       [ 1.34323237,  1.13942894, -0.51509849, -0.24640332],
       [-0.29614765,  0.51499413,  1.81505468,  0.05736391],
       [ 0.64426393,  0.52334275,  1.28471008,  0.77966144]])

In [105]:
np.sum(data)

np.float64(6.037324568128161)

In [ ]:
np.sum(data, axis= 1 )

array([-1.0070782 ,  1.7211595 ,  2.09126507,  3.2319782 ])

In [108]:
np.sum(data, axis= 0)

array([ 1.88962168,  1.08269757,  3.54202014, -0.47701483])

In [121]:
n1 = np.sum(data[:, 1:], axis= 1 )
n1

array([-1.20535124,  0.37792712,  2.38741272,  2.58771427])

In [123]:
data2 =np.random.randn(3,5)
data2

array([[-0.28266489,  2.34694076, -0.36321219,  0.53009119,  0.76216142],
       [ 1.85876491,  1.50305594,  0.55653509,  0.4781593 ,  1.33521365],
       [ 0.62304687,  0.6592261 , -0.52273303,  0.46875478,  1.43206999]])

In [ ]:
# 요소의 평균값
np.mean(data2)

np.float64(0.7590273260970203)

In [127]:
np.mean(data2 , axis=0)

array([ 0.73304897,  1.50307427, -0.10980337,  0.49233509,  1.17648169])

In [126]:
np.mean(data2 , axis=1)

array([0.59866326, 1.14634578, 0.53207294])

In [ ]:
np.min(data2 ,axis=1)

array([-0.36321219,  0.4781593 , -0.52273303])

In [130]:
# 표준편차
np.std(data2)

np.float64(0.7891734897061674)

In [131]:
# 분산
np.var(data2)

np.float64(0.6227947968550104)

In [ ]:
np.sort(data2)

array([[-1.09506825, -1.06763686,  0.19827304,  0.95735387],
       [-0.51509849, -0.24640332,  1.13942894,  1.34323237],
       [-0.29614765,  0.05736391,  0.51499413,  1.81505468],
       [ 0.52334275,  0.64426393,  0.77966144,  1.28471008]])

In [134]:
np.sort(data2 , axis=0)

array([[-0.28266489,  0.6592261 , -0.52273303,  0.46875478,  0.76216142],
       [ 0.62304687,  1.50305594, -0.36321219,  0.4781593 ,  1.33521365],
       [ 1.85876491,  2.34694076,  0.55653509,  0.53009119,  1.43206999]])

In [ ]:
stu1 = [85,90,88,92]
stu2 = [78,81,85,86]
stu3 = [92,88,91,90]
stu4 = [70,75,72,78]
stu5 = [88,85,84,89]

sc = np.array([stu1,stu2,stu3,stu4,stu5])
avg = np.mean (sc, axis=1)
stable = np.std(sc, axis=1)
over90_counts = (sc >= 90).sum(axis=1)
max_over90_idx = np.argmax(over90_counts)

min_std_idx = np.argmin(stable)
stu_with_min_std = sc[min_std_idx]
print("각 학생의 평균점수: ",avg)
print(f"표준편차가 가장 낮은 학생: stu{min_std_idx+1} ->", sc[min_std_idx])
print(f"90 이상이 가장 많은 학생: stu{max_over90_idx+1} ->", sc[max_over90_idx])



각 학생의 평균점수:  [88.75 82.5  90.25 73.75 86.5 ]
표준편차가 가장 낮은 학생: stu3 -> [92 88 91 90]
90 이상이 가장 많은 학생: stu3 -> [92 88 91 90]
